### ISSUE TITLE
Unexpected crash on Yosemite

### ISSUE THREAD

**Issue by mbektimirov** [mjolnirapp/mjolnir#524]
Didn't get the pattern yet, but mjolnir just halting when I use it with console.

**Comment by cmsj** [comment]
I think it's because MJConsoleWindowController instructs the console's NSTextView to append text without ensuring it happens on the main thread, where UI work is done. Switching out the call to [[self.outputView textStorage] appendAttributedString:attrstr] with one that performs that call on the main thread, should fix this.
